
### PEDIDO

GET http://localhost:8888/index.php/grupo HTTP/1.1

###

DELETE http://localhost:8888/index.php/grupo/1 HTTP/1.1


###

POST http://localhost:8888/index.php/grupo HTTP/1.1
Content-Type: application/json

{
    "grupNombre":"Camionetas",
    "grupDescripcion":"Camionetas Toyota modelo 2016"
}


###

PUT http://localhost:8888/index.php/grupo HTTP/1.1

{
    "grupId": 1,
    "grupNombre": "Camionetas",
    "grupDescripcion": "Camionetas Toyota modelo nuevo"
  }

###
Send Request
GET http://localhost:8888/index.php/tarea HTTP/1.1
###

GET http://localhost:8888/index.php/servicio HTTP/1.1

###
POST http://localhost:8888/index.php/servicio_tarea  HTTP/1.1
Content-Type: application/json

{
  "setaServId": 1,
  "setaTareId": 1,
  "tareNombre": "test1",
}

###

GET http://localhost:8888/index.php/grupo_servicio HTTP/1.1
###
GET http://localhost:8888/index.php/movil_servicio HTTP/1.1

### movil-odometro


GET http://localhost:8888/index.php/movil HTTP/1.1

